import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import './styles.css'
import './hero.css'
import './hero-flow.css'
import './warp-overrides.css'
import './single-title.css'
import './apple-position.css'
import './about-reference.css'
import './about-rebuild.css'
import './static-glow.css'
import './about-layout-fix.css'
import './about-photo.css'
import './about-echo.css'
import './about-warp.css'
import './walker-work.css'
import './section-transition.css'
import './case-cards.css'
import './nav-links.css'
import App from './App.jsx'

createRoot(document.getElementById('root')).render(<StrictMode><App /></StrictMode>)
